version: '2.3'
services:
  redis:
    image: redis:5.0.3
    ports:
      - "6379:6379"

  service:
    image: registry.insight-centre.org/sit/mps/felipe-phd/model-trainer:dev
    command: echo "ok"
    build:
      context: '.'
      dockerfile: 'Dockerfile'

  rpi-builder:
    image: registry.insight-centre.org/sit/mps/felipe-phd/model-trainer:builder-latest-rpi
    command: echo "ok"
    build:
      context: '.'
      dockerfile: 'Dockerfile_builder.rpi'
    volumes:
      - "./:/app"